[tool.portray.mkdocs.theme]
favicon = "art/logo_small.png"
logo = "art/logo_small.png"
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
	[[tool.portray.mkdocs.nav.Tutorials]]
		"1. Generating fake data files" = "docs/tutorials/tutorial1.md"

	[[tool.portray.mkdocs.nav.Tutorials]]
		"2. Templates and conditional logic" = "docs/tutorials/tutorial2.md"

	[[tool.portray.mkdocs.nav.Tutorials]]
		"3. Lookups and transformers" = "docs/tutorials/tutorial3.md"

[[tool.portray.mkdocs.nav]]
	[[tool.portray.mkdocs.nav."How to"]]
		"Create a custom field" = "docs/how-to/create-custom-field.md"

	[[tool.portray.mkdocs.nav."How to"]]
		"Create custom transformer" = "docs/how-to/create-custom-transformer.md"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
fail-under = 95
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
